<a href="https://colab.research.google.com/github/committed-kermit/ClassicML/blob/main/MultipleLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
from sklearn.datasets import make_regression

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [53]:
X,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [54]:
df=pd.DataFrame({'feature 1':X[:,0],'feature 2':X[:,1],'target':y})

In [55]:
df.head()

   feature 1  feature 2     target
0  -0.990937  -0.557340 -82.112839
1   0.201923   0.940286  16.018197
2   0.350592   1.000809 -36.507726
3   0.700574  -1.286580  53.343622
4   0.728447   0.183046 -11.324588

In [56]:
df.sample(15)

    feature 1  feature 2      target
51  -0.487639  -0.623086 -138.298828
81  -0.315359   0.870190  -59.022815
12   0.463630   1.173774   -2.207067
77   0.362174  -1.447559  125.828408
53   1.332465   0.767252  137.553644
29  -0.601058   0.286732 -137.941038
31  -0.497188   1.806118  -42.889535
25   0.395520  -1.463683  105.182517
59   0.588963  -1.012429  102.102101
61   1.079991  -1.090675  113.923373
99   1.034296  -0.146523  197.798551
67  -1.358736   0.232706 -110.024942
19  -0.017534   0.775448   39.442124
75  -0.632439  -0.894329 -122.244832
22   0.136828  -0.062728  -12.324714

In [57]:
fig=px.scatter_3d(df,x='feature 1',y='feature 2',z='target')
fig.show()

In [58]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=3)

In [59]:
lr=LinearRegression()

In [60]:
lr.fit(X_train,y_train)

LinearRegression()

In [61]:
y_pred=lr.predict(X_test)

In [62]:
print('MAE:',mean_absolute_error(y_test,y_pred))
print('MSE:',mean_squared_error(y_test,y_pred))
print('RMSE:',np.sqrt(mean_squared_error(y_test,y_pred)))

MAE: 52.130876429306156
MSE: 4466.801079659568
RMSE: 66.83413109826122

In [63]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)

z = z_final

In [72]:
fig = px.scatter_3d(df, x='feature 1', y='feature 2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z, opacity=0.3 ))

fig.show()

In [73]:
y_pred_original_data = lr.predict(X)

fig.add_trace(go.Scatter3d(x=df['feature 1'], y=df['feature 2'], z=y_pred_original_data, mode='markers', marker=dict(color='red', size=3), name='Predicted Points on Plane'))

fig.show()

In [65]:
lr.coef_

array([93.12244916, 16.17329589])

In [66]:
lr.intercept_

np.float64(-0.42003399308692657)