<a href="https://colab.research.google.com/github/committed-kermit/ClassicML/blob/main/Multiple-Linear-Regression-Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [ ]:
X,y=load_diabetes(return_X_y=True,as_frame=True)

In [ ]:
X.sample(5)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
189,-0.001882,-0.044642,-0.066563,0.001215,-0.002945,0.003070,0.011824,-0.002592,-0.020292,-0.025930
238,0.034443,0.050680,-0.009439,0.059744,-0.035968,-0.007577,-0.076536,0.071210,0.011011,-0.021788
284,0.041708,0.050680,-0.022373,0.028758,-0.066239,-0.045155,-0.061809,-0.002592,0.002861,-0.054925
10,-0.096328,-0.044642,-0.083808,0.008101,-0.103389,-0.090561,-0.013948,-0.076395,-0.062917,-0.034215
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025953,-0.054925

In [ ]:
y.sample(5)

214     65.0
166     70.0
419     42.0
175    127.0
220     78.0
Name: target, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
y_train

70      48.0
37     276.0
170     47.0
400    175.0
286     60.0
       ...
299     83.0
22      68.0
72     202.0
15     171.0
168    268.0
Name: target, Length: 353, dtype: float64

In [ ]:
class meraMLR:

  def __init__(self):
    self.coef_=None
    self.intercept_=None

  def fit(self,X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)

    betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_=betas[0]
    self.coef_=betas[1:]

  def predict(self,X_test):
    y_pred=np.dot(X_test,self.coef_)+self.intercept_
    return y_pred

In [ ]:
mlr=meraMLR()

In [ ]:
mlr.fit(X_train,y_train)

In [ ]:
mlr.predict(X_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.1671215 ,
       145.46179904, 117.65702433, 168.88784311, 198.38683887,
       118.24053714, 124.64552812, 223.17700368, 200.63012386,
       129.54414666, 158.1584765 , 154.332565  , 114.47070769,
        70.44906407,  76.3973879 , 172.41584591,  80.56270077,
        80.2722834 ,  89.46150248, 186.21572052, 275.46275403,
       208.26784222, 143.79451509, 291.28766846, 206.32474844,
        94.22935404])

In [ ]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,mlr.predict(X_test))
print(r2*100,'%')

43.99338661568963 %

In [ ]:
mlr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
mlr.intercept_

np.float64(151.88331005254165)